import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  booksSidebar: [{ type: 'autogenerated', dirName: 'books' }],

  charactersSidebar: [{ type: 'autogenerated', dirName: 'characters' }],

  worldSidebar: [{ type: 'autogenerated', dirName: 'world' }],
};

export default sidebars;
